services:
  - type: web
    name: trilha
    runtime: node
    plan: free
    branch: walking-tracker-app-0134e
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: admin@teste.com
      - key: ADMIN_PASSWORD
        sync: false
